### ISSUE TITLE
Difference between this and postcss-import?

### ISSUE THREAD

**Issue by simonsmith** [sebastian-software/postcss-smart-import#26]
It looks very similar, down to the README copy. What are the main differences? Curious if it has solved any of the issues with 8.x of `postcss-import`

Thanks!

**Comment by swernerx** [comment]
It's up-do-date with postcss-import but does not support media queries anymore (making things cleaner). It supports multiple style extensions with there corresponding parsers out of the box e.g. sugarSS. There are also plans for integrating url handling and asset handling.

**Comment by toomuchdesign** [comment]
First of all thank's @swernerx for the great work here.
I'm integrating postcss-smart-import into my workflow and it's currently working great!

Since It's a fork of postcss-import v.8, did you manage to solve the [wrong import order issues](https://github.com/postcss/postcss-import/issues/211) precisely introduced in unlucky v.8? I still haven't had the time to test it in a complex dependency scenario.

Thanks again for you time! Cheers.

**Comment by QuantumInformation** [comment]
Not supporting media queries? I use them all the time in Less.

**Comment by simonsmith** [comment]
@QuantumInformation I think he was referring to this style:

```css
@import "css/bar.css" (min-width: 25em);
```

@toomuchdesign The import issues have been fixed

**Comment by toomuchdesign** [comment]
@simonsmith I replaced `postcss-import` with `postcss-smart-import` in project of mine involving a quite complex @import's scenario and I confirm that it's working great! Thank's again!!

**Comment by simonsmith** [comment]
Just to clarify, the issue was fixed first in `postcss-import` and then [merged into this fork](https://github.com/sebastian-software/postcss-smart-import/commit/cdc81287c18086306f44612315418fd08208ee58) so either plugin will now work as expected.

**Comment by QuantumInformation** [comment]
what does URl and asset give me over postcss-import?
