### ISSUE TITLE
@import ignored when inside :global block

### ISSUE THREAD

**Issue by eriklharper** [sebastian-software/postcss-smart-import#45]
```
.default {
  width: 100%;
  height: 100%;

  :global {
    @import "leaflet/dist/leaflet.css";

    .leaflet-container {
      width: 100%;
      height: 100%;
      background-color: transparent;
    }
  }
}
```
☝️ `@import` is totally ignored in this case.  Why?

Expected behavior:
```
.default {
  width: 100%;
  height: 100%;

  :global {
    /*.... contents of node_modules/leaflet/dist/leaflet.css */

    .leaflet-container {
      width: 100%;
      height: 100%;
      background-color: transparent;
    }
  }
}
```
FYI, I'm using `postcss-nested` which allows me to wrap `:global` around stuff and it concats all of its children with the `:global` prefix just like how it works in Sass.  I'm also using `css-modules` so the `.default` class becomes a hashed class name, so doing this allows me to wrap leaflet's global styles in my hashed css module, keeping those leaflet classes from polluting my global css.

Also as you can see I'm overriding default leaflet styles right below the import, so this makes inlining overrides on vendor stylesheets clean and in the same spot.

These fail as well:
```
.default {
  @import "./foo.css";
  :global {
    .App {
      background-color: red;
      text-align: center;
    }
  }
}
```
```
.default {
  :global {
    .App {
      background-color: red;
      text-align: center;
    }
  }
}
@import "./foo.css";
```

**Comment by swernerx** [comment]
@import is meant to be top-level only.

**Comment by eriklharper** [comment]
Sounds like you want your plugin to support the official spec, which is fine, but then again I ask, if you're going to go the trouble of writing a separate import plugin, why not make it more flexible so that other use cases like this can be used with it?  Guess I'll have to try writing my own...

**Comment by leebenson** [comment]
@eriklharper, I'm in exactly the same boat as you - I need `@import` to basically act as a concat for stuff that appears within a `:global` block, an  Did you wind up writing your own plugin? Would be very interested in using it, thanks.

**Comment by eriklharper** [comment]
Yeah, just took the time to publish it on npm, so you should be able to do `npm install --save-dev postcss-nested-import` or `yarn add postcss-nested-import`

https://github.com/eriklharper/postcss-nested-import

Would love to get some others feedback on this.  Thanks!

**Comment by leebenson** [comment]
@swernerx, IMO I think this should be re-looked at.

You're right that `@import` is top-level only, but the _exception_ to that is `:global` which isn't really a nested statement, but rather an marker to css-modules that what appears within the block shouldn't be converted to local classnames.

Since that's such a common wrapper for literally every Webpack config that css loading, it makes sense that a developer might want to wrap some `@import` statements in a `:global` block in order to mean 'import and preserve imported classnames'.

As you can see in https://github.com/jonathantneal/postcss-partial-import/issues/35, it seems to be a pretty common request. Implementing in-place imports wouldn't hinder the more traditional top-level use case for `@import`. If a user wants it top-level, they can just keep it top-level without it being enforced.
